# Generated by Django 2.2.4 on 2020-03-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_auto_20190902_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cards_cut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=1500),
        ),
    ]
