# Generated by Django 2.2.4 on 2020-03-30 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0003_auto_20200327_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cutter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='standings.Player')),
            ],
        ),
    ]
