# Generated by Django 2.2.4 on 2020-03-31 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0004_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cards_cut',
        ),
    ]
